Fix for issues 256 & 239.
alallier/reload pull request #262
Opened 2020-08-16 15:33 UTC by vineethbc

The http server error is being handled gracefully with error message & reload increments the port & tries again.
https://github.com/alallier/reload/issues/256
https://github.com/alallier/reload/issues/239

2020-09-29 20:00 UTC, alallier requested changes
This all looks good, just one feedback/action item

2020-09-29 20:00 UTC, alallier commented on bin/reload
> +    program.port++
Can we add an on by default flag option for the auto increment?

2020-12-10 10:38 UTC, porst17 commented
Any chance for this being merged soon?

I created something like this in https://github.com/porst17/reload/commit/549e4fbb9682b7351e944946e4f612d09bb52e8d using the `portfinder` package, not being aware of the work done in this pull request.

But having a solution like yours that doesn't add another dependency is probably preferable.

2020-12-10 13:23 UTC, alallier commented
@porst17 I have this basically done and re-worked in a separate branch. I should be able to get this up soon.

2022-02-04 00:55 UTC, closed without merging